"""add client tax return document models

Revision ID: 23214eaf19eb
Revises: 
Create Date: 2026-04-18 18:00:26.956438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23214eaf19eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('client_type', sa.String(length=80), nullable=False),
    sa.Column('primary_contact_name', sa.String(length=255), nullable=True),
    sa.Column('primary_contact_email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('sharepoint_folder_url', sa.String(length=1024), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_display_name'), ['display_name'], unique=False)

    op.create_table('tax_returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('return_type', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True),
    sa.Column('reviewer_user_id', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('sharepoint_return_folder_url', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tax_returns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tax_returns_assigned_user_id'), ['assigned_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_returns_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_returns_reviewer_user_id'), ['reviewer_user_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tax_return_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('original_file_type', sa.String(length=50), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('document_type', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('sharepoint_file_url', sa.String(length=1024), nullable=True),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['tax_return_id'], ['tax_returns.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_tax_return_id'), ['tax_return_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_uploaded_by_user_id'), ['uploaded_by_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_uploaded_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_documents_tax_return_id'))
        batch_op.drop_index(batch_op.f('ix_documents_client_id'))

    op.drop_table('documents')
    with op.batch_alter_table('tax_returns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tax_returns_reviewer_user_id'))
        batch_op.drop_index(batch_op.f('ix_tax_returns_client_id'))
        batch_op.drop_index(batch_op.f('ix_tax_returns_assigned_user_id'))

    op.drop_table('tax_returns')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_display_name'))

    op.drop_table('clients')
    # ### end Alembic commands ###
